import type { RSSSubscription } from './types';

export const DEFAULT_RSS_SUBSCRIPTIONS: RSSSubscription[] = [
  {
    id: 'rss-openai-news',
    title: 'OpenAI News',
    url: 'https://openai.com/news/rss.xml',
    siteUrl: 'https://openai.com/news',
    category: 'ai-product',
    description: 'OpenAI 官方新闻与产品更新。',
    enabled: true,
  },
  {
    id: 'rss-huggingface-blog',
    title: 'Hugging Face Blog',
    url: 'https://huggingface.co/blog/feed.xml',
    siteUrl: 'https://huggingface.co/blog',
    category: 'ai-product',
    description: '模型、工具链与开源 AI 产品动态。',
    enabled: true,
  },
  {
    id: 'rss-google-research',
    title: 'Google Research',
    url: 'https://research.google/blog/rss/',
    siteUrl: 'https://research.google/blog/',
    category: 'ai',
    description: 'Google Research 的 AI 与研究博客。',
    enabled: true,
  },
  {
    id: 'rss-arxiv-cs-ai',
    title: 'arXiv cs.AI',
    url: 'https://rss.arxiv.org/rss/cs.AI',
    siteUrl: 'https://arxiv.org/list/cs.AI/recent',
    category: 'ai',
    description: 'AI 方向论文增量流，适合盯研究前沿。',
    enabled: true,
  },
  {
    id: 'rss-github-trending',
    title: 'GitHub Trending',
    url: 'https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml',
    siteUrl: 'https://github.com/trending',
    category: 'github',
    description: 'GitHub 日榜趋势仓库聚合流。',
    enabled: true,
  },
  {
    id: 'rss-psychological-science',
    title: 'Psychological Science',
    url: 'https://journals.sagepub.com/action/showFeed?jc=pssa&type=etoc&feed=rss',
    siteUrl: 'https://journals.sagepub.com/home/pss',
    category: 'psychology-journal',
    description: '心理学顶刊之一，偏广义实验与认知研究。',
    enabled: true,
  },
  {
    id: 'rss-perspectives-psychological-science',
    title: 'Perspectives on Psychological Science',
    url: 'https://journals.sagepub.com/action/showFeed?jc=ppsa&type=etoc&feed=rss',
    siteUrl: 'https://journals.sagepub.com/home/pps',
    category: 'psychology-journal',
    description: '偏综述与观点，适合快速把握心理学议题。',
    enabled: true,
  },
  {
    id: 'rss-clinical-psychological-science',
    title: 'Clinical Psychological Science',
    url: 'https://journals.sagepub.com/action/showFeed?jc=cpxa&type=etoc&feed=rss',
    siteUrl: 'https://journals.sagepub.com/home/cpx',
    category: 'psychology-journal',
    description: '临床心理学顶级期刊流。',
    enabled: true,
  },
  {
    id: 'rss-current-directions-psychological-science',
    title: 'Current Directions in Psychological Science',
    url: 'https://journals.sagepub.com/action/showFeed?jc=cdpa&type=etoc&feed=rss',
    siteUrl: 'https://journals.sagepub.com/home/cdp',
    category: 'psychology-journal',
    description: '高密度综述流，适合脱水式阅读。',
    enabled: true,
  },
  {
    id: 'rss-nature-human-behaviour',
    title: 'Nature Human Behaviour',
    url: 'https://www.nature.com/nathumbehav.rss',
    siteUrl: 'https://www.nature.com/nathumbehav/',
    category: 'psychology',
    description: '行为科学与心理学交叉前沿。',
    enabled: true,
  },
];
